version: '3.8'

networks:
  nginx-php80-mysql8:

services:
  
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php80-service
      - mysql8-service
    networks:
      - nginx-php80-mysql8
  
  # php
  php80-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php80-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    networks:
      - nginx-php80-mysql8
  
  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    networks:
      - nginx-php80-mysql8
  

